#%RAML 1.0 NamedExample
value:
 -
  InsurancId: 1
  InsuranceName: Bajaj aliance
  ContactNumber: 9999999999
  Quotation: Oriental Health 250000 5 Personal accidental cover 8888888888

 -
  InsurancId: 3
  InsuranceName: LIC
  ContactNumber: 9999000000
  Quotation: Oriental Health 250000 5 family Corona cover 8888888888

 -
  InsurancId: 5
  InsuranceName: SBI Insurance
  ContactNumber: 8888999999
  Quotation: Oriental Health 250000 5 Personal accidental cover 8888888888